# Generated by Django 6.0 on 2026-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibeapp', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
