# Generated by Django 6.0 on 2026-03-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibeapp', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('follow_request', 'Request'), ('accept', 'Accepted Request')], max_length=20),
        ),
    ]
