# Generated by Django 6.0 on 2026-03-15 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibeapp', '0013_reel_message_shared_reel_reelcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_reels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reel',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_reels', to=settings.AUTH_USER_MODEL),
        ),
    ]
